apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: phlbrz/kube-news:v3
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        env:
          - name:  DB_PASSWORD
            value: "Pg#123"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_HOST
            value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubenews
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubenews
            port:
              number: 80